In [1]:
import numpy as np
np.__version__
data=[[1,2,3],[4,5,6],[7,8,9]]
a = np.array(data)          # 배열 만들기
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
a.astype(float)            #원소 타입 설정 가능

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
a[1][2] #2행 3열(0부터 시작)

6

In [4]:
np.arange(1,10,2)         # 1부터 10까지 2씩 (시작,끝,공차)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1,10).reshape(3,3)   #일렬의 수열로 행렬만들기 (reshape로 행렬의 모양을 만들수 있음. 3차원 행렬 가능)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,13).reshape(3,2,2)   #일렬의 수열로 행렬만들기 (3*2*2 3차원 행렬(tensor))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [7]:
np.nan*10                

nan

In [8]:
a[0][1]=np.nan                 #실수형만 nan값 설정 가능. 정수형은 불가능

ValueError: cannot convert float NaN to integer

In [9]:
np.linspace(1,10,10)          #시작 끝 몇개, 1차원 배열 만들기 => 벡터

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
## 사칙연산 가능

In [11]:
data1 = np.arange(1,10).reshape(3,3)
data2 = np.arange(11,20).reshape(3,3)

In [12]:
data1+data2                 #원소의 합 구현 가능하다

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [13]:
data1 - data2            #원소의 차

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [14]:
data1 * data2            #원소의 곱

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [161]:
data1 / data2           #원소의 나눗셈

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [162]:
data1 // data2           #원소의 나눗셈(몫)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [16]:
np.dot(data1,data2)     # 행렬의 곱

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [157]:
data1@data2             #행렬의 곱

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

그외 연산자

In [163]:
data1%4              #원소의 나눗셈(나머지)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [165]:
-data1               #음수

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [166]:
data1**2            #제곱

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [180]:
data3=-(np.arange(8).reshape(2,4))
data3=np.vstack([data3,-data3])
data3

array([[ 0, -1, -2, -3],
       [-4, -5, -6, -7],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [182]:
abs(data3)             #절댓값 가능

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
#0차원 스칼라
a=np.array(1)                  #대괄호[]를 사용하지 않아 하나의 숫자만 들어간 것으로 침. 스칼라 값으로 0차원.
a
a.shape #없음
a.ndim #0

0

In [19]:
#1차원 벡터
a=np.array([1])                #대괄호[]를 사용하여 하나의 행에 하나의 원소가 들어간 1*1 행렬으로 볼 수 있다.
a
a.shape #(1,)
a.ndim #1

1

In [20]:
#1차원 벡터
a=np.array([1,2,3,4,5])          #1*5행렬   => 선형이므로 벡터로 볼 수 있다. linspce()로도 만들 수 있다.
a
# a.shape #(5,)                    #어째서인지 5*1 전치행렬(벡터)처럼 표현된다.
a.ndim #1

1

In [21]:
#1차원 벡터
a=np.array([1,2,3,4,5])          #1*5행렬   => 선형이므로 벡터로 볼 수 있다.
a=a.reshape(5,1)
a.shape #(5,1)                  
a                                #실제 5*1 행렬은 각 행을 []단위로 묶어 5행 1렬로 표현된다.

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
#1차원 벡터
a=np.array([1,2,3,4,5])          #1*5행렬   => 선형이므로 벡터로 볼 수 있다.
a=a.reshape(1,5)
a.shape #(1,5)                   
a                                #실제 1*5 행렬은 위의 벡터와 달리 이중대괄호[[]]로 표현되어 안쪽 괄호 안이 하나의 행임을 보인다.

array([[1, 2, 3, 4, 5]])

In [23]:
#2차원 행렬
a=np.array([[1,2,3],[4,5,6]])
a
# a.shape #(2,3) 2행 3열  2*3행렬임.
# a.ndim #2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#3차원 tensor텐서
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
a
# a.shape #(2,2,3)    2*2*3 3차원 텐서.
# a.ndim #3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
a=np.arange(12).reshape(2,2,3)            #원소를 0부터 n까지의 n개의 수로 채운 배열 만들기
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
b= np.ones(12).reshape(2,2,3)             #모든 원소를 1로 채운 배열 만들기
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
c=np.zeros(12).reshape(2,3,2)             #모든 원소를 0으로 채운 배열 만들기
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
d=np.eye(3)                              #n by n 단위행렬 만들기
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
e=np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
f=np.empty([2,3])      # empty를 사용할 경우 zeros와 다른 결과를 얻음
f                      ##0에 가까운 매우 작은 수

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
g = np.full([3,4],1000)          #0과 1 이외의 숫자로 모두 채울때 사용
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [32]:
h=np.linspace(2,100,6)           #시작, 끝, 갯수 => 범위 내에서 갯수만큼의 항을 갖는 선형 등차수열 만들기
h                               #각 원소가 등차 -> 시작 끝을 갯수만큼 자른 구간

array([  2. ,  21.6,  41.2,  60.8,  80.4, 100. ])

In [33]:
h=np.arange(2,100,6)           #시작, 끝, 공차 => 범위 내에서 공차만큼 커지는 선형 등차수열 만들기
h                               #각 원소가 등차 -> 시작 끝을 갯수만큼 자른 구간

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 98])

In [34]:
np.random.random((3,3))          #random.random => 0~1 사이 난수로 채움

array([[0.70513967, 0.25596957, 0.48227182],
       [0.47857079, 0.34912564, 0.53829658],
       [0.87764019, 0.54602743, 0.57919931]])

In [35]:
np.random.randint(1,20,(3,3))   #random.randint => 범위내의 정수 난수로 채움

array([[ 7,  3,  5],
       [17,  9, 18],
       [16, 19, 12]])

In [36]:
np.random.normal(0,1,(3,3))    #정규분포(평균,표준편차)의 난수로 채움

array([[ 0.94310786,  0.98599658, -0.05580174],
       [ 0.73646444,  0.03438156, -1.63642206],
       [-0.60046553, -0.24577392,  1.9087923 ]])

# 집계함수

In [37]:
a= np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
a[0][0]=10                        #원소의 수정이 가능하다
a

array([[10,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [214]:
a[0,1]=100
a

array([[[  1,   2],
        [100, 100]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]]])

In [222]:
l=np.arange(1,6)
np.add.reduce(l)   #reduce는 결과만 저장(표시)

15

In [224]:
l=np.arange(1,6)
np.multiply.reduce(l)   #reduce는 결과만 저장(표시)

120

In [226]:
l=np.arange(1,6)
np.add.accumulate(l)   #accumulate는 중간과정 저장(표시)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [227]:
l=np.arange(1,6)
np.multiply.accumulate(l)   #accumulate는 중간과정 저장(표시)

array([  1,   2,   6,  24, 120], dtype=int32)

In [220]:
l=np.arange(1,7).reshape(2,3)
l,    np.add.reduce(l), np.add.reduce(l,axis=1)   #reduce는 결과만 저장(표시)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([5, 7, 9]),
 array([ 6, 15]))

In [228]:
l=np.arange(1,7).reshape(2,3)
l,    np.add.accumulate(l), np.add.accumulate(l,axis=1)   #accumulate는 중간과정 저장(표시)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [5, 7, 9]], dtype=int32),
 array([[ 1,  3,  6],
        [ 4,  9, 15]], dtype=int32))

In [229]:
l=np.arange(1,7).reshape(2,3)
l,    np.multiply.reduce(l), np.multiply.reduce(l,axis=1)   #reduce는 결과만 저장(표시)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([ 4, 10, 18]),
 array([  6, 120]))

In [230]:
l=np.arange(1,7).reshape(2,3)
l,    np.multiply.accumulate(l), np.multiply.accumulate(l,axis=1)   #accumulate는 중간과정 저장(표시)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3],
        [ 4, 10, 18]], dtype=int32),
 array([[  1,   2,   6],
        [  4,  20, 120]], dtype=int32))

In [40]:
np.mean(a) #평균

15.4

In [41]:
np.median(a) #중앙값

6.5

In [42]:
np.var(a) #분산

801.2399999999999

In [43]:
np.std(a) #표준편차

28.306183070135045

In [44]:
np.sum(a) #모든 원소 합

154

In [45]:
sum(a) #각 행간 합

array([ 15, 106,   9,  11,  13])

In [46]:
np.sum(a, axis=0) #각 행간 합

array([ 15, 106,   9,  11,  13])

In [47]:
np.sum(a, axis=1) #각 열간 합

array([119,  35])

In [48]:
np.max(a) , np.min(a)    #최대, 최소

(100, 2)

In [49]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a.shape

(3, 2, 2)

다차원 슬라이싱

In [57]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
arr[:2,:3]   #2개 행 3개 열 슬라이싱

array([[1, 2, 3],
       [6, 7, 8]])

In [59]:
arr[:2,::-2]    #2개 행 뒤에서 부터 2칸씩

array([[ 5,  3,  1],
       [10,  8,  6]])

In [62]:
arr[::-2,::-1]   #뒤에서 2칸씩 행, 뒤에서부터 열

array([[25, 24, 23, 22, 21],
       [15, 14, 13, 12, 11],
       [ 5,  4,  3,  2,  1]])

In [66]:
arr_sub=arr[:2,:2]
arr_sub[0,0] = 99
arr, arr_sub                          #사본/일부 사본 복사 후 변경시 원본도 변경

(array([[99,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[99,  2],
        [ 6,  7]]))

In [67]:
arr_copy=arr[:2,:2].copy()
arr_copy[0,0]=88
arr, arr_copy                          #사본/일부 사본 복사 후 변경시 원본은 변경 안됨

(array([[99,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[88,  2],
        [ 6,  7]]))

In [71]:
arr[:,np.newaxis]      #각 행을 하나의 원소로 열벡터를 만듬

array([[[99,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25]]])

In [72]:
arr[np.newaxis,:]      #각 행을 하나의 원소로 행벡터를 만듬

array([[[99,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]])

In [94]:
arr1=[1,2,3]
arr2=[4,5,6]
arr3=[7,8,9]
arr4=np.concatenate([arr1,arr2,arr3])    # 배열연결
arr4 = arr4.reshape(3,3)
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
import copy
arr5=[]
for i in arr4:
    arr5.append(i+9)
arr5 = np.array(arr5).reshape(3,3)
arr5

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [101]:
arr6 = np.concatenate([arr4,arr5])
arr6        #밑에 붙임

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [103]:
arr6 = np.concatenate([arr4,arr5],axis=1)
arr6        #옆에 붙임

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [115]:
arr7 = np.vstack([arr4,arr5])      #수직스택
arr7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [117]:
arr7 = np.hstack([arr4,arr5])      #수평스택
arr7

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [122]:
x=np.arange(25).reshape(5,5)
y1,y2,y3= np.split(x,[2,4])
y1,y2,y3

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]]))

In [125]:
x=np.arange(25).reshape(5,5)
z = np.hsplit(x,[3])
w = np.vsplit(x,[2])
z ,w

([array([[ 0,  1,  2],
         [ 5,  6,  7],
         [10, 11, 12],
         [15, 16, 17],
         [20, 21, 22]]),
  array([[ 3,  4],
         [ 8,  9],
         [13, 14],
         [18, 19],
         [23, 24]])],
 [array([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
  array([[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]])])

In [131]:
arr[0][0]=1
2**arr,arr**2

(array([[       2,        4,        8,       16,       32],
        [      64,      128,      256,      512,     1024],
        [    2048,     4096,     8192,    16384,    32768],
        [   65536,   131072,   262144,   524288,  1048576],
        [ 2097152,  4194304,  8388608, 16777216, 33554432]], dtype=int32),
 array([[  1,   4,   9,  16,  25],
        [ 36,  49,  64,  81, 100],
        [121, 144, 169, 196, 225],
        [256, 289, 324, 361, 400],
        [441, 484, 529, 576, 625]], dtype=int32))

In [153]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [151]:
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([1.        , 0.5       , 0.33333333, 0.2       , 0.33333333])

In [156]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)
%timeit (1.0/big_array)

2.14 s ± 9.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.63 ms ± 15 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [183]:
print(compute_reciprocals(values))
print(1.0/values)

[1.         0.5        0.33333333 0.2        0.33333333]
[1.         0.5        0.33333333 0.2        0.33333333]


삼각함수

In [184]:
theta = np.linspace(0,np.pi,3)

In [198]:
import math
print(theta)
print(np.cos(theta))
print(np.sin(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [203]:
x=[1,2,3,4,10]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(2,x))
print(np.power(3,x))
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[1, 2, 3, 4, 10]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 2.20264658e+04]
[   2.    4.    8.   16. 1024.]
[   2    4    8   16 1024]
[    3     9    27    81 59049]
[0.         0.69314718 1.09861229 1.38629436 2.30258509]
[0.         1.         1.5849625  2.         3.32192809]
[0.         0.30103    0.47712125 0.60205999 1.        ]


In [207]:
print(np.log1p(x))             #log(x+1)
print(np.expm1(x))             #exp(x)-1

[0.69314718 1.09861229 1.38629436 1.60943791 2.39789527]
[1.71828183e+00 6.38905610e+00 1.90855369e+01 5.35981500e+01
 2.20254658e+04]


In [231]:
x=np.arange(5)
y=np.zeros(5)
z=np.zeros(10)
np.multiply(x,10,out=y)
np.power(2,x,out=z[::2])
y, z

(array([ 0., 10., 20., 30., 40.]),
 array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.]))

외적

In [238]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [255]:
x = np.arange(1,6).reshape(1,5)
y = np.arange(1,6).reshape(5,1)
y@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [243]:
x = [1,0,0]
y = [0,1,0]
np.multiply.outer(x,y)

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

브로드캐스팅

In [4]:
import numpy as np
p = [0,1,2]
o = [3,4,5]
p+o                 #넘파이 아니면 그냥 리스트 연결

[0, 1, 2, 3, 4, 5]

In [7]:
p = np.array([0,1,2])
o = np.array([3,4,5])
p+o                 #길이 같은 배열끼리는 원소끼리 합

array([3, 5, 7])

In [15]:
p+4                 #배열+실수 => 실수합은 원소에 각각 합

array([4, 5, 6])

In [17]:
p*4                 #배열+실수 => 실수배는 원소에 각각 곱

array([0, 4, 8])

In [11]:
m = np.ones((3,3))
m+p                 #행의 길이가 같으면 각 행에 합도 가능

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [27]:
q=p.reshape(3,1)
p+q                #열벡터 + 행벡터 => 열벡터의 각 원소를 행벡터에 실수합하고 결과를 저장함

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [26]:
r=np.arange(1,7).reshape(3,2)
r+p         #모양이 아예 안맞으면(행의 갯수가 안맞으면) 에러

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [33]:
m=np.ones((2,3))
a=np.arange(3)
m, a, m+a

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2]),
 array([[1., 2., 3.],
        [1., 2., 3.]]))

In [34]:
m.shape, a.shape

((2, 3), (3,))

브로드캐스팅 규칙
1. a.shape -> (1,3)
2. a.shape -> (2,3)(복사해서 행 늘리기)
3. m+a

In [35]:
X = np.random.random((10,3))

In [38]:
Xmean =X.mean(0)
X, Xmean

(array([[0.48092378, 0.1990093 , 0.19613045],
        [0.44149588, 0.82063383, 0.75253703],
        [0.68864601, 0.88294071, 0.89885715],
        [0.28051654, 0.8730566 , 0.58085678],
        [0.44427587, 0.04847316, 0.67385757],
        [0.10378344, 0.64538704, 0.35110433],
        [0.39651548, 0.3868966 , 0.26465243],
        [0.91037048, 0.45466616, 0.96532662],
        [0.07926845, 0.98426436, 0.84475663],
        [0.68860651, 0.67302363, 0.30177855]]),
 array([0.45144024, 0.59683514, 0.58298575]))

In [39]:
Xcenterd = X-Xmean
Xcenterd.mean(0)

array([ 0.00000000e+00,  2.22044605e-17, -4.44089210e-17])