In [2]:
import pandas as pd
import numpy as np

In [16]:
data = np.arange(0,50,10)
data

array([ 0, 10, 20, 30, 40])

In [17]:
data1 = pd.Series(data, index = ['a','b','c','d','e'])
data1

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [18]:
data2 = pd.Series(data)
data2

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [19]:
data1['b']

10

In [20]:
data1.loc['b']

10

In [22]:
data1.iloc[1]

10

In [28]:
data1+10
data1-10
data1*10
data1**10
data1 //5

a    0
b    2
c    4
d    6
e    8
dtype: int32

In [29]:
data1 >15

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [30]:
data[data>15]

array([20, 30, 40])

In [32]:
data1.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int32

In [33]:
data1.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int32

In [34]:
data1.mul(10)

a      0
b    100
c    200
d    300
e    400
dtype: int32

In [35]:
data1.div(10)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [37]:
data1.mod(4)

a    0
b    2
c    0
d    2
e    0
dtype: int32

In [38]:
data1.min()

0

In [39]:
data1.max()

40

In [40]:
data1.sum()

100

In [42]:
data1.mean()

20.0

In [43]:
data1.median()

20.0

In [44]:
data1.var()

250.0

In [45]:
data1.std()

15.811388300841896

In [47]:
rawdata = np.random.randint(50,100,size =(4,3))
rawdata

array([[84, 95, 80],
       [64, 78, 96],
       [72, 73, 86],
       [89, 82, 99]])

In [92]:
df = pd.DataFrame(rawdata, index=['1반','2반','1반','2반'], columns=['국','영','수'])
df

국   영   수
1반  84  95  80
2반  64  78  96
1반  72  73  86
2반  89  82  99

In [93]:
df['국']

1반    84
2반    64
1반    72
2반    89
Name: 국, dtype: int32

In [55]:
# df[0] #에러

In [94]:
df['평균']= round((df['국']+df['영']+df['수'])/3,2)
df

국   영   수     평균
1반  84  95  80  86.33
2반  64  78  96  79.33
1반  72  73  86  77.00
2반  89  82  99  90.00

In [95]:
df['na']=np.nan
df

국   영   수     평균  na
1반  84  95  80  86.33 NaN
2반  64  78  96  79.33 NaN
1반  72  73  86  77.00 NaN
2반  89  82  99  90.00 NaN

In [96]:
del df['na']
df

국   영   수     평균
1반  84  95  80  86.33
2반  64  78  96  79.33
1반  72  73  86  77.00
2반  89  82  99  90.00

In [97]:
df[df.평균>80]

국   영   수     평균
1반  84  95  80  86.33
2반  89  82  99  90.00

In [98]:
df= df.drop(['평균'],axis='columns')
df

국   영   수
1반  84  95  80
2반  64  78  96
1반  72  73  86
2반  89  82  99

결측값 처리

In [99]:
df = df.astype('float')
df

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
1반  72.0  73.0  86.0
2반  89.0  82.0  99.0

In [100]:
df['수'][2] = np.nan
df

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
1반  72.0  73.0   NaN
2반  89.0  82.0  99.0

In [101]:
df.dropna(axis=0)

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
2반  89.0  82.0  99.0

In [102]:
df.dropna(axis=1)

국     영
1반  84.0  95.0
2반  64.0  78.0
1반  72.0  73.0
2반  89.0  82.0

In [103]:
# df.dropna(axis=0,inplace=True)
df

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
1반  72.0  73.0   NaN
2반  89.0  82.0  99.0

In [104]:
df.fillna('hell')

국     영     수
1반  84.0  95.0    80
2반  64.0  78.0    96
1반  72.0  73.0  hell
2반  89.0  82.0    99

In [105]:
df.fillna(0)

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
1반  72.0  73.0   0.0
2반  89.0  82.0  99.0

In [108]:
df.fillna(df.sum())

국     영      수
1반  84.0  95.0   80.0
2반  64.0  78.0   96.0
1반  72.0  73.0  275.0
2반  89.0  82.0   99.0

In [109]:
df.fillna(df.mean())

국     영          수
1반  84.0  95.0  80.000000
2반  64.0  78.0  96.000000
1반  72.0  73.0  91.666667
2반  89.0  82.0  99.000000

multiindex

In [110]:
df

국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0
1반  72.0  73.0   NaN
2반  89.0  82.0  99.0

In [112]:
df.T #전치

1반    2반    1반    2반
국  84.0  64.0  72.0  89.0
영  95.0  78.0  73.0  82.0
수  80.0  96.0   NaN  99.0

In [117]:
df.index=[['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df

국     영     수
1학년 1반  84.0  95.0  80.0
    2반  64.0  78.0  96.0
2학년 1반  72.0  73.0   NaN
    2반  89.0  82.0  99.0

In [122]:
df.columns=[['언어','언어','수리'],['국','영','수']]
df

언어          수리
           국     영     수
1학년 1반  84.0  95.0  80.0
    2반  64.0  78.0  96.0
2학년 1반  72.0  73.0   NaN
    2반  89.0  82.0  99.0

In [127]:
df['언어']

국     영
1학년 1반  84.0  95.0
    2반  64.0  78.0
2학년 1반  72.0  73.0
    2반  89.0  82.0

In [128]:
df['언어']['국']

1학년  1반    84.0
     2반    64.0
2학년  1반    72.0
     2반    89.0
Name: 국, dtype: float64

In [129]:
df.iloc[0]

언어  국    84.0
    영    95.0
수리  수    80.0
Name: (1학년, 1반), dtype: float64

In [133]:
df.loc['1학년']

언어          수리
       국     영     수
1반  84.0  95.0  80.0
2반  64.0  78.0  96.0

In [136]:
df.loc['1학년'].loc['1반']

언어  국    84.0
    영    95.0
수리  수    80.0
Name: 1반, dtype: float64

데이터 사전 분석

In [138]:
df

언어          수리
           국     영     수
1학년 1반  84.0  95.0  80.0
    2반  64.0  78.0  96.0
2학년 1반  72.0  73.0   NaN
    2반  89.0  82.0  99.0

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 248.0+ bytes


In [141]:
df.head() #앞의 5개

언어          수리
           국     영     수
1학년 1반  84.0  95.0  80.0
    2반  64.0  78.0  96.0
2학년 1반  72.0  73.0   NaN
    2반  89.0  82.0  99.0

In [143]:
df.tail() #끝의 5개

언어          수리
           국     영     수
1학년 1반  84.0  95.0  80.0
    2반  64.0  78.0  96.0
2학년 1반  72.0  73.0   NaN
    2반  89.0  82.0  99.0

In [145]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [146]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   77.250000  82.000000  91.666667
std    11.354148   9.416298  10.214369
min    64.000000  73.000000  80.000000
25%    70.000000  76.750000  88.000000
50%    78.000000  80.000000  96.000000
75%    85.250000  85.250000  97.500000
max    89.000000  95.000000  99.000000

In [147]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [148]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

값의 연결

In [150]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [151]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int32

In [153]:
pd.concat([a,b],axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [154]:
pd.concat([a,b],axis=1,ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [157]:
a.append([b],ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30